# Generated by Django 2.2 on 2024-01-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitc2', models.PositiveSmallIntegerField(blank=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Source',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField(blank=True)),
                ('values', models.BigIntegerField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_year_data', to='dataAnalysis.Product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_year_data', to='dataAnalysis.Source')),
            ],
            options={
                'verbose_name_plural': 'YearData',
            },
        ),
    ]
