# Generated by Django 2.2 on 2024-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='values',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='year',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
