# Generated by Django 2.2 on 2024-01-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0002_auto_20240112_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sitc2',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
