# Generated by Django 2.2 on 2024-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0003_auto_20240112_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeardata',
            name='values',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
