# Generated by Django 2.2 on 2024-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0004_auto_20240112_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeardata',
            name='values',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='year',
            field=models.SmallIntegerField(default=0),
        ),
    ]
