# Generated by Django 2.2 on 2024-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
    ]
