# Generated by Django 2.2 on 2024-01-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='title',
            new_name='color',
        ),
    ]
