# Generated by Django 2.2 on 2024-01-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
