# Generated by Django 2.2 on 2024-02-21 07:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0004_auto_20240126_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='saved_btn',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
