# Generated by Django 2.2 on 2024-02-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0005_city_saved_btn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='saved_btn',
        ),
    ]
