# Generated by Django 2.2 on 2024-02-21 12:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0006_remove_city_saved_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='save_btn',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
