# Generated by Django 2.2 on 2024-01-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=700)),
            ],
            options={
                'verbose_name_plural': 'County',
            },
        ),
        migrations.CreateModel(
            name='CountyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.SmallIntegerField(default=0)),
                ('value_data', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_data', to='county.County')),
            ],
            options={
                'verbose_name_plural': 'CountyValue',
            },
        ),
    ]
