# Generated by Django 2.2 on 2024-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyvalue',
            name='value_data',
            field=models.IntegerField(null=True),
        ),
    ]
