# Generated by Django 2.2 on 2024-01-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tennisclub',
            options={'ordering': ['id'], 'verbose_name_plural': 'TennisClub'},
        ),
    ]
