# Generated by Django 2.2 on 2024-03-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240326_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='blog.Languages'),
        ),
    ]
