# Generated by Django 2.2 on 2024-03-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_title', to='blog.Topic'),
        ),
    ]
