# Generated by Django 2.2 on 2024-01-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ueconomics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='yeardata',
            options={'ordering': ['id'], 'verbose_name_plural': 'YearData'},
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='value',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='year',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
