# Generated by Django 2.2 on 2024-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ueconomics', '0002_auto_20240111_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
    ]
