# Generated by Django 2.2 on 2024-02-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ueconomics', '0003_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
