# Generated by Django 2.2 on 2024-02-29 16:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=600)),
                ('save_btn', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
    ]
