# Generated by Django 2.2 on 2024-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
                ('guessed_word', models.CharField(max_length=100)),
                ('attempts_left', models.CharField(default=6, max_length=10)),
            ],
        ),
    ]
