# Generated by Django 2.2 on 2024-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_auto_20240404_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attempts_left',
            field=models.IntegerField(default=6),
        ),
    ]
