# Generated by Django 2.2 on 2024-01-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name_plural': 'Client'},
        ),
    ]
