# Generated by Django 2.2 on 2024-01-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='color',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
